/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Case: typeof import('./components/Case.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Showcase: typeof import('./components/Showcase.vue')['default']
  }
}
