name: Vercel Regular Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Install Vercel CLI
        if: env.VERCEL_ORG_ID != ''
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        if: env.VERCEL_ORG_ID != ''
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        if: env.VERCEL_ORG_ID != ''
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        if: env.VERCEL_ORG_ID != ''
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
